packages:
  - ./todo

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  eslint>ajv: ^6.12.4
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  hono@<4.11.4: '>=4.11.4'
  minimatch@<10.2.1: '>=10.2.1'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
